version: '3'

services:


  myappbluebank-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=@compilers9
      - MYSQL_DATABASE=bluebank
      - MYSQL_USER=devcompilers
      - MYSQL_PASSWORD=@compilers9
    ports:
      - 3306:3306

  myapp-main:
    image: squad-devcompilers/bluebank
    restart: on-failure
    depends_on:
      - myappbluebank-mysql
    ports:
      - 5000:5000
    environment:
      - DATABASE_HOST=myappbluebank-mysql
      - DATABASE_USER=devcompilers
      - DATABASE_PASSWORD=@compilers9
      - DATABASE_NAME=bluebank
      - DATABASE_PORT=3306
